"--------
" vundle and plugins
"--------
set nocompatible
filetype off

" set the runtime path (customerized location) 
" to include Vundle and initialize (again, with customerized
" location for packages
set rtp+=~/Documents/packages/vim/bundle/Vundle.vim
call vundle#begin('~/Documents/packages/vim/bundle')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ctrlpvim/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line




"--------
" vim configuration
"--------
syntax on

set autoindent
set expandtab
set shiftwidth=2 
set softtabstop=2

set hlsearch
